import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { rm, mkdir, writeFile, mkdtemp, access } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runBundleBuild } from '../../src/commands/bundle-build.js';
import { detectBundleAtCwd } from '../../src/bundle/config.js';
import { captureOutput } from '../helpers/cli-fixtures.js';

// ============================================================
// TEMP DIR TRACKING
// ============================================================

const tmpDirs: string[] = [];

async function makeTmpDir(): Promise<string> {
  const dir = await mkdtemp(path.join(os.tmpdir(), 'rill-bundle-build-test-'));
  tmpDirs.push(dir);
  return dir;
}

// Save the real cwd before each test and restore it in afterEach so that
// buildPackage's internal process.chdir() does not leave the process in a
// deleted tmpdir when afterEach cleans up.
let savedCwd = process.cwd();

beforeEach(() => {
  savedCwd = process.cwd();
});

afterEach(async () => {
  process.chdir(savedCwd);
  for (const dir of tmpDirs.splice(0)) {
    await rm(dir, { recursive: true, force: true }).catch(() => undefined);
  }
});

// ============================================================
// FIXTURE HELPERS
// ============================================================

/**
 * Write a minimal rill-bundle.json to bundleDir.
 */
async function writeBundleJson(
  bundleDir: string,
  content: Record<string, unknown>
): Promise<void> {
  await writeFile(
    path.join(bundleDir, 'rill-bundle.json'),
    JSON.stringify(content, null, 2),
    'utf-8'
  );
}

/**
 * Initialize the .rill/npm workspace so buildPackage's bootstrap check passes.
 */
async function initRillNpm(projectDir: string): Promise<void> {
  const rillNpmDir = path.join(projectDir, '.rill', 'npm');
  await mkdir(rillNpmDir, { recursive: true });
  await writeFile(
    path.join(rillNpmDir, 'package.json'),
    JSON.stringify({ name: 'rill-extensions', private: true }, null, 2),
    'utf-8'
  );
}

/**
 * Create a minimal buildable package directory under bundleDir.
 * Returns the relative project path (relative to bundleDir).
 */
async function makePackageFixture(
  bundleDir: string,
  relPath: string,
  overrides: { name?: string; version?: string; main?: string } = {}
): Promise<void> {
  const projectDir = path.join(bundleDir, relPath);
  await mkdir(projectDir, { recursive: true });

  const config = {
    name: overrides.name ?? path.basename(relPath),
    version: overrides.version ?? '0.1.0',
    main: overrides.main ?? 'main.rill:run',
  };

  await writeFile(
    path.join(projectDir, 'rill-config.json'),
    JSON.stringify(config, null, 2),
    'utf-8'
  );
  await writeFile(path.join(projectDir, 'main.rill'), `"hello"`, 'utf-8');
  await initRillNpm(projectDir);
}

/**
 * Write a fake harness module at <bundleDir>/.rill/npm/node_modules/<name>/.
 * The module exports a default RillHarness with the given postBuild behaviour.
 *
 * When writesMainJs is true, postBuild writes build/main.js.
 * When writesMainJs is false, postBuild does nothing (main.js absent).
 */
async function writeFakeHarnessModule(
  bundleDir: string,
  moduleName: string,
  writesMainJs: boolean
): Promise<void> {
  const npmRoot = path.join(bundleDir, '.rill', 'npm');
  const modDir = path.join(npmRoot, 'node_modules', moduleName);
  await mkdir(modDir, { recursive: true });

  // Ensure the .rill/npm/package.json marker exists for createRequire resolution
  const npmPkgJson = path.join(npmRoot, 'package.json');
  if (!existsSync(npmPkgJson)) {
    await writeFile(
      npmPkgJson,
      JSON.stringify({ name: 'rill-extensions', private: true }, null, 2),
      'utf-8'
    );
  }

  await writeFile(
    path.join(modDir, 'package.json'),
    JSON.stringify(
      { name: moduleName, version: '0.1.0', type: 'module', main: 'index.js' },
      null,
      2
    ),
    'utf-8'
  );

  const postBuildBody = writesMainJs
    ? `  const { writeFile } = await import('node:fs/promises');
  const mainPath = ctx.outputDir + '/main.js';
  await writeFile(mainPath, '// generated by fake harness\\n', 'utf-8');`
    : `  // intentionally does not write main.js`;

  const harnessSrc = `
export default {
  name: '${moduleName}',
  postBuild: async function(ctx) {
${postBuildBody}
  },
};
`.trimStart();

  await writeFile(path.join(modDir, 'index.js'), harnessSrc, 'utf-8');
}

// ============================================================
// TEST: 3-package bundle — concurrent compile, postBuild invoked once, main.js, exit 0
// ============================================================

describe('runBundleBuild', () => {
  it('builds 3 packages concurrently, invokes postBuild once, emits build/main.js, exits 0', async () => {
    const bundleDir = await makeTmpDir();

    await makePackageFixture(bundleDir, 'packages/pkg-alpha', {
      name: 'pkg-alpha',
    });
    await makePackageFixture(bundleDir, 'packages/pkg-beta', {
      name: 'pkg-beta',
    });
    await makePackageFixture(bundleDir, 'packages/pkg-gamma', {
      name: 'pkg-gamma',
    });

    await writeBundleJson(bundleDir, {
      name: 'test-bundle',
      version: '1.0.0',
      packages: [
        { mount: 'pkg-alpha', project: 'packages/pkg-alpha' },
        { mount: 'pkg-beta', project: 'packages/pkg-beta' },
        { mount: 'pkg-gamma', project: 'packages/pkg-gamma' },
      ],
    });

    const out = captureOutput();
    let exitCode: number;
    try {
      exitCode = await runBundleBuild(bundleDir, {});
    } finally {
      out.restore();
    }

    expect(exitCode).toBe(0);
    // build/main.js must exist (written by builtin postBuild)
    const mainJsPath = path.join(bundleDir, 'build', 'main.js');
    await expect(access(mainJsPath)).resolves.toBeUndefined();
    // postBuild logs appear exactly once
    const combined = out.stdout.join('');
    expect(combined).toContain('running harness postBuild');
    expect(combined.indexOf('running harness postBuild')).toBe(
      combined.lastIndexOf('running harness postBuild')
    );
  });

  // ============================================================
  // TEST: omitted harness field uses built-in; exit 0
  // ============================================================

  it('uses built-in harness when harness field is absent', async () => {
    const bundleDir = await makeTmpDir();

    await makePackageFixture(bundleDir, 'packages/only-pkg', {
      name: 'only-pkg',
    });

    // No `harness` field in config
    await writeBundleJson(bundleDir, {
      name: 'builtin-bundle',
      version: '1.0.0',
      packages: [{ mount: 'only-pkg', project: 'packages/only-pkg' }],
    });

    const out = captureOutput();
    let exitCode: number;
    try {
      exitCode = await runBundleBuild(bundleDir, {});
    } finally {
      out.restore();
    }

    expect(exitCode).toBe(0);
    const mainJsPath = path.join(bundleDir, 'build', 'main.js');
    await expect(access(mainJsPath)).resolves.toBeUndefined();
  });

  // ============================================================
  // TEST: one package build failure — others complete, harness NOT invoked, exit 1
  // ============================================================

  it('returns exit 1 when one package fails; does not invoke harness postBuild', async () => {
    const bundleDir = await makeTmpDir();

    // Good packages
    await makePackageFixture(bundleDir, 'packages/good-a', { name: 'good-a' });
    await makePackageFixture(bundleDir, 'packages/good-b', { name: 'good-b' });

    // Bad package: missing .rill/npm/package.json so buildPackage throws
    const badPkgDir = path.join(bundleDir, 'packages', 'bad-pkg');
    await mkdir(badPkgDir, { recursive: true });
    await writeFile(
      path.join(badPkgDir, 'rill-config.json'),
      JSON.stringify({
        name: 'bad-pkg',
        version: '0.1.0',
        main: 'main.rill:run',
      }),
      'utf-8'
    );
    await writeFile(path.join(badPkgDir, 'main.rill'), `"hello"`, 'utf-8');
    // Deliberately omit .rill/npm/package.json — buildPackage will throw

    await writeBundleJson(bundleDir, {
      name: 'partial-failure-bundle',
      version: '1.0.0',
      packages: [
        { mount: 'good-a', project: 'packages/good-a' },
        { mount: 'good-b', project: 'packages/good-b' },
        { mount: 'bad-pkg', project: 'packages/bad-pkg' },
      ],
    });

    const out = captureOutput();
    let exitCode: number;
    try {
      exitCode = await runBundleBuild(bundleDir, {});
    } finally {
      out.restore();
    }

    expect(exitCode).toBe(1);
    // Harness postBuild must NOT have been invoked
    const combined = out.stdout.join('');
    expect(combined).not.toContain('running harness postBuild');
    // Error message must mention the failing package
    const errCombined = out.stderr.join('');
    expect(errCombined).toContain('bad-pkg');
  });

  // ============================================================
  // TEST: declared harness postBuild does not write build/main.js → stderr, exit 1
  // ============================================================

  it('returns exit 1 and writes to stderr when declared harness postBuild omits build/main.js', async () => {
    const bundleDir = await makeTmpDir();
    const harnessName = 'fake-harness-no-main';

    await makePackageFixture(bundleDir, 'packages/solo', { name: 'solo' });
    await writeFakeHarnessModule(bundleDir, harnessName, false);

    await writeBundleJson(bundleDir, {
      name: 'no-main-bundle',
      version: '1.0.0',
      harness: harnessName,
      packages: [{ mount: 'solo', project: 'packages/solo' }],
    });

    const out = captureOutput();
    let exitCode: number;
    try {
      exitCode = await runBundleBuild(bundleDir, {});
    } finally {
      out.restore();
    }

    expect(exitCode).toBe(1);
    const errCombined = out.stderr.join('');
    expect(errCombined).toContain('build/main.js');
  });

  // ============================================================
  // TEST: declared harness field references unresolvable module → stderr with module name, exit 1
  // ============================================================

  it('returns exit 1 and mentions the module name when declared harness cannot be resolved', async () => {
    const bundleDir = await makeTmpDir();
    const harnessName = 'nonexistent-harness-xyz123';

    // Initialize the .rill/npm root so createRequire has a valid base
    await mkdir(path.join(bundleDir, '.rill', 'npm'), { recursive: true });
    await writeFile(
      path.join(bundleDir, '.rill', 'npm', 'package.json'),
      JSON.stringify({ name: 'rill-extensions', private: true }),
      'utf-8'
    );

    await makePackageFixture(bundleDir, 'packages/solo', { name: 'solo' });

    await writeBundleJson(bundleDir, {
      name: 'bad-harness-bundle',
      version: '1.0.0',
      harness: harnessName,
      packages: [{ mount: 'solo', project: 'packages/solo' }],
    });

    const out = captureOutput();
    let exitCode: number;
    try {
      exitCode = await runBundleBuild(bundleDir, {});
    } finally {
      out.restore();
    }

    expect(exitCode).toBe(1);
    const errCombined = out.stderr.join('');
    expect(errCombined).toContain(harnessName);
  });

  // ============================================================
  // TEST: both rill-bundle.json and rill-config.json present — bundle mode wins
  // ============================================================

  it('reads only rill-bundle.json and ignores rill-config.json when both exist', async () => {
    const bundleDir = await makeTmpDir();

    await makePackageFixture(bundleDir, 'packages/only-pkg', {
      name: 'only-pkg',
    });

    await writeBundleJson(bundleDir, {
      name: 'dual-config-bundle',
      version: '1.0.0',
      packages: [{ mount: 'only-pkg', project: 'packages/only-pkg' }],
    });

    // Write a rill-config.json in bundleDir that would make things fail if read
    await writeFile(
      path.join(bundleDir, 'rill-config.json'),
      JSON.stringify({ name: 'invalid-if-read', main: 'SHOULD_NOT_BE_USED' }),
      'utf-8'
    );

    const out = captureOutput();
    let exitCode: number;
    try {
      exitCode = await runBundleBuild(bundleDir, {});
    } finally {
      out.restore();
    }

    // runBundleBuild reads rill-bundle.json only; build must succeed
    expect(exitCode).toBe(0);
    const mainJsPath = path.join(bundleDir, 'build', 'main.js');
    await expect(access(mainJsPath)).resolves.toBeUndefined();
  });

  // ============================================================
  // TEST: two packages mount the same extension at different paths — both resolve, no duplication
  // ============================================================

  it('builds two packages that share a bundle-level .rill/npm without duplicating it', async () => {
    const bundleDir = await makeTmpDir();

    // Place an extension directory at the bundle-level .rill/npm to represent a
    // shared dependency. Both packages build successfully without touching it,
    // and runBundleBuild must not write into or duplicate that location.
    const bundleNpmRoot = path.join(bundleDir, '.rill', 'npm');
    const sentinel = path.join(bundleNpmRoot, 'node_modules', 'sentinel-pkg');
    await mkdir(sentinel, { recursive: true });
    await writeFile(
      path.join(bundleNpmRoot, 'package.json'),
      JSON.stringify({ name: 'rill-extensions', private: true }),
      'utf-8'
    );
    await writeFile(
      path.join(sentinel, 'package.json'),
      JSON.stringify({ name: 'sentinel-pkg', version: '1.0.0' }),
      'utf-8'
    );

    // Two plain packages with no extensions — they each have their own .rill/npm
    // but share the bundle-level npm root as a structural sibling.
    await makePackageFixture(bundleDir, 'packages/pkg-one', {
      name: 'pkg-one',
    });
    await makePackageFixture(bundleDir, 'packages/pkg-two', {
      name: 'pkg-two',
    });

    await writeBundleJson(bundleDir, {
      name: 'shared-npm-bundle',
      version: '1.0.0',
      packages: [
        { mount: 'pkg-one', project: 'packages/pkg-one' },
        { mount: 'pkg-two', project: 'packages/pkg-two' },
      ],
    });

    const out = captureOutput();
    let exitCode: number;
    try {
      exitCode = await runBundleBuild(bundleDir, {});
    } finally {
      out.restore();
    }

    expect(exitCode).toBe(0);

    // Both packages must appear in the build output
    const buildDir = path.join(bundleDir, 'build');
    expect(existsSync(path.join(buildDir, 'pkg-one'))).toBe(true);
    expect(existsSync(path.join(buildDir, 'pkg-two'))).toBe(true);

    // The bundle-level .rill/npm and its sentinel must remain intact — not
    // modified, moved, or duplicated by the build orchestration
    await expect(
      access(path.join(sentinel, 'package.json'))
    ).resolves.toBeUndefined();
    // runBundleBuild must not have written a duplicate node_modules at bundleDir root
    expect(existsSync(path.join(bundleDir, 'node_modules'))).toBe(false);
  });
});

// ============================================================
// TEST: detectBundleAtCwd — packages/<name>/ subdirectory
// ============================================================

describe('detectBundleAtCwd', () => {
  it('returns false when cwd is inside packages/<name>/ within a bundle', async () => {
    const bundleDir = await makeTmpDir();
    await writeBundleJson(bundleDir, {
      name: 'test-bundle',
      version: '1.0.0',
      packages: [],
    });
    await mkdir(path.join(bundleDir, 'packages', 'pkg-one'), {
      recursive: true,
    });

    expect(detectBundleAtCwd(path.join(bundleDir, 'packages', 'pkg-one'))).toBe(
      false
    );
  });
});
